site_name: My Docs
site_url: https://jaxyz.github.io
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - navigation.tabs
  # navigation_depth: 5

# markdown_extensions:
#   # - pymdownx.arithmatex:
#   #     generic: true
#   #     tex_inline_wrap: ["$", "$"]
#   - pymdownx.arithmatex

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      # tex_inline_wrap: ['$', '$']
      # tex_block_wrap: ['$$', '$$']
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  - mathjax/es5/tex-mml-chtml.js

plugins:
  - literate-nav:
      nav_file: navigation.md
  - macros
